# This workflow is used to run benchmarktests based on the unittest framework

name: Benchmark tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  benchmark:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        include:
        - operating-system: macos-latest
          python-version: '3.12'
          label: osx-64-py-3-12
          prefix: /Users/runner/miniconda3/envs/my-env

        - operating-system: windows-latest
          python-version: '3.12'
          label: win-64-py-3-12
          prefix: C:\Miniconda3\envs\my-env
          
        - operating-system: ubuntu-latest
          python-version: '3.12'
          label: linux-64-py-3-12
          prefix: /usr/share/miniconda3/envs/my-env

    steps:
    - uses: actions/checkout@v4
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        activate-environment: my-env
        environment-file: .ci_support/environment.yml
        use-mamba: true
    - name: Tests
      shell: bash -l {0}
      timeout-minutes: 30
      run: |
        python .ci_support/pyironconfig.py
        bash .ci_support/pip_install.sh
        python -m unittest discover test_benchmarks
