# This workflow is used to run benchmarktests based on the unittest framework

name: Benchmark tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  benchmark:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        include:
        - operating-system: macos-latest
          python-version: '3.12'

        - operating-system: windows-latest
          python-version: '3.12'
          
        - operating-system: ubuntu-latest
          python-version: '3.12'

    steps:
    - uses: actions/checkout@v4
    - name: Conda config
      run: echo -e "channels:\n  - conda-forge\n" > .condarc
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-version: latest
        condarc-file: .condarc
        environment-file: .ci_support/environment.yml
    - name: Tests
      shell: bash -l {0}
      timeout-minutes: 30
      run: |
        python .ci_support/pyironconfig.py
        bash .ci_support/pip_install.sh
        python -m unittest discover tests/benchmarks
