# This workflow is used to run the unittest of pyiron

name: Broken Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        include:
        - operating-system: macos-latest
          python-version: '3.12'
          label: osx-64-latest-py-3-12
          prefix: /Users/runner/miniconda3/envs/my-env

        - operating-system: macos-11
          python-version: '3.12'
          label: osx-64-11-py-3-12
          prefix: /Users/runner/miniconda3/envs/my-env

        - operating-system: macos-12
          python-version: '3.12'
          label: osx-64-12-py-3-12
          prefix: /Users/runner/miniconda3/envs/my-env

        - operating-system: macos-13
          python-version: '3.12'
          label: osx-64-13-py-3-12
          prefix: /Users/runner/miniconda3/envs/my-env

        - operating-system: macos-14
          python-version: '3.12'
          label: osx-64-14-py-3-12
          prefix: /Users/runner/miniconda3/envs/my-env

    steps:
    - uses: actions/checkout@v4
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        activate-environment: my-env
        environment-file: .ci_support/environment.yml
        use-mamba: true
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 2
      run: |
        python .ci_support/pyironconfig.py
        bash .ci_support/pip_install.sh
        python tests/table/test_datamining.py TestProjectDataParallel.test_parallel
