# This workflow is used to run the unittest of pyiron

name: Minimal

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Conda config
      run: echo -e "channels:\n  - conda-forge\n" > .condarc
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: '3.12'
        miniforge-version: latest
        condarc-file: .condarc
        environment-file: .ci_support/environment-mini.yml
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 10
      run: |
        python .ci_support/pyironconfig.py
        bash .ci_support/pip_install.sh
        python -m unittest discover tests/unit
