name: Push-Pull

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pyiron:
    uses: pyiron/actions/.github/workflows/push-pull.yml@pyiron_base_lessons
    secrets: inherit
    with:
      do-commit-updated-env: false
      do-build-docs: false  # the build-docs action tries to use sphinx, not jupyterbook
      unit-test-dir: tests
      coveralls-and-codacy-test-dir: tests
      benchmark-test-dir: test_benchmarks
      alternate-tests-env-files: .ci_support/environment-old.yml
      alternate-tests-python-version: '3.9'
      omit-patterns: pyiron_base/_version.py,tests/*