# This workflow is used to run the unittest of pyiron

name: Unittests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        include:
        - operating-system: macos-latest
          python-version: '3.12'
          label: osx-64-py-3-12

        - operating-system: windows-latest
          python-version: '3.12'
          label: win-64-py-3-12

        - operating-system: ubuntu-latest
          python-version: '3.12'
          label: linux-64-py-3-12
          
        - operating-system: ubuntu-latest
          python-version: '3.11'
          label: linux-64-py-3-11

    steps:
    - uses: actions/checkout@v4
    - name: Conda config
      shell: bash -l {0}
      run: echo -e "channels:\n  - conda-forge\n" > .condarc
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-version: latest
        condarc-file: .condarc
        environment-file: .ci_support/environment.yml
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 10
      run: |
        python .ci_support/pyironconfig.py
        bash .ci_support/pip_install.sh
        coverage run --omit="pyiron_base/_version.py,tests/*" -m unittest discover tests/unit
        coverage xml
    - name: Coveralls
      if: matrix.label == 'linux-64-py-3-11'
      uses: coverallsapp/github-action@v2
